name: nnlsm-cpu
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip:
      - torch==2.3.1+cpu
      - torchvision==0.18.1+cpu
      - torchaudio==2.3.1+cpu
      - --index-url https://download.pytorch.org/whl/cpu
